# Predicting Dengue Spread

## Project Overview

In this project I examine features impacting the occurrence of Dengue Fever and employ several machine learning models to predict its spread. Dengue surveillance data is provided by the U.S. Centers for Disease Control and prevention, as well as the Department of Defense's Naval Medical Research Unit 6 and the Armed Forces Health Surveillance Center, in collaboration with the Peruvian government and U.S. universities. Environmental and climate data is provided by the National Oceanic and Atmospheric Administration (NOAA), an agency of the U.S. Department of Commerce.
The project is part of the "Predict the Next Pandemic Initiative"

The data set is hosted at Driven Data, which provides datasets that explore social and humanitarian issues. They also host machine learning competitions, similar to Kaggle, but the overarching goal of all competitions is to provides some sort of humanitarian benefit. It's machine learning with a heart!

Here is a link to Driven Data: https://www.drivendata.org/ 
More information on the Dengue issue can be found here: https://www.drivendata.org/competitions/44/dengai-predicting-disease-spread/page/81/

If you are unfamiliar with Dengue Fever (it is uncommon in the US), is a mosquito-borne tropical disease common in more than 110 countries, mainly in Asia and South America. Each year between 50 and 528 million people are infected and approximately 10,000 to 20,000 die.
The Wikipedia page is a good resource: https://en.wikipedia.org/wiki/Dengue_fever

And here is some info on the life cycle of the mosquito: https://www.cdc.gov/dengue/resources/factSheets/MosquitoLifecycleFINAL.pdf

### Here are the starting features

City and date indicators
* city – City abbreviations: sj for San Juan and iq for Iquitos
* week_start_date – Date given in yyyy-mm-dd format

NOAA's GHCN daily climate data weather station measurements
* station_max_temp_c – Maximum temperature
* station_min_temp_c – Minimum temperature
* station_avg_temp_c – Average temperature
* station_precip_mm – Total precipitation
* station_diur_temp_rng_c – Diurnal temperature range

PERSIANN satellite precipitation measurements (0.25x0.25 degree scale)
* precipitation_amt_mm – Total precipitation

NOAA's NCEP Climate Forecast System Reanalysis measurements (0.5x0.5 degree scale)
* reanalysis_sat_precip_amt_mm – Total precipitation
* reanalysis_dew_point_temp_k – Mean dew point temperature
* reanalysis_air_temp_k – Mean air temperature
* reanalysis_relative_humidity_percent – Mean relative humidity
* reanalysis_specific_humidity_g_per_kg – Mean specific humidity
* reanalysis_precip_amt_kg_per_m2 – Total precipitation
* reanalysis_max_air_temp_k – Maximum air temperature
* reanalysis_min_air_temp_k – Minimum air temperature
* reanalysis_avg_temp_k – Average air temperature
* reanalysis_tdtr_k – Diurnal temperature range

Satellite vegetation - Normalized difference vegetation index (NDVI) - NOAA's CDR Normalized Difference Vegetation Index (0.5x0.5 degree scale) measurements
* ndvi_se – Pixel southeast of city centroid
* ndvi_sw – Pixel southwest of city centroid
* ndvi_ne – Pixel northeast of city centroid
* ndvi_nw – Pixel northwest of city centroid

### Target Variable

The target we are investigating is "totol cases", which is a specifies for each city, year, and weekofyear.

#### Lets begin:

In [14]:
import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
%run ./functions.ipynb

In [30]:
data_path = []
for dirname, _, filenames in os.walk('.\data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        data_path.append(os.path.join(dirname, filename))

.\data\dengue_features_train.csv
.\data\dengue_labels_train.csv

In [31]:
# Load the data
print(data_path[0])
print(data_path[1])

.\data\dengue_features_train.csv
.\data\dengue_labels_train.csv

In [32]:
df_feat = pd.read_csv(data_path[0], index_col=[0,1,2])
df_targ = pd.read_csv(data_path[1], index_col=[0,1,2])
#print(df_targ.columns)

## Data Exploration

In [24]:
# df_o will be our original dataframe, which will be left untouched
df_o=pd.concat([df_feat,df_targ.total_cases],axis=1)
df_o.sample(5)
#df_o.columns

                     week_start_date   ndvi_ne   ndvi_nw   ndvi_se   ndvi_sw  \
city year weekofyear
iq   2006 7               2006-02-19  0.382700  0.250600  0.243657  0.285600
sj   1991 44              1991-10-29  0.094000  0.096650  0.125567  0.121317
     2001 12              2001-03-19  0.127433  0.059925  0.159229  0.140886
     1990 22              1990-05-28  0.196200  0.262200  0.251200  0.247340
     1996 19              1996-05-06 -0.046400 -0.038400  0.096400  0.094457

                      precipitation_amt_mm  reanalysis_air_temp_k  \
city year weekofyear
iq   2006 7                          44.35             297.064286
sj   1991 44                         72.61             299.905714
     2001 12                          0.00             298.372857
     1990 22                          7.52             299.518571
     1996 19                          0.00             297.710000

                      reanalysis_avg_temp_k  reanalysis_dew_point_temp_k  \
city year weekofyear
iq   2006 7                      298.142857                   295.364286
sj   1991 44                     299.992857                   295.918571
     2001 12                     298.592857                   293.045714
     1990 22                     299.664286                   295.821429
     1996 19                     297.800000                   292.915714

                      reanalysis_max_air_temp_k  ...  \
city year weekofyear                             ...
iq   2006 7                               305.2  ...
sj   1991 44                              302.4  ...
     2001 12                              300.3  ...
     1990 22                              301.9  ...
     1996 19                              299.4  ...

                      reanalysis_relative_humidity_percent  \
city year weekofyear
iq   2006 7                                      91.098571
sj   1991 44                                     78.987143
     2001 12                                     72.442857
     1990 22                                     80.460000
     1996 19                                     74.792857

                      reanalysis_sat_precip_amt_mm  \
city year weekofyear
iq   2006 7                                  44.35
sj   1991 44                                 72.61
     2001 12                                  0.00
     1990 22                                  7.52
     1996 19                                  0.00

                      reanalysis_specific_humidity_g_per_kg  \
city year weekofyear
iq   2006 7                                       16.927143
sj   1991 44                                      17.375714
     2001 12                                      14.482857
     1990 22                                      17.210000
     1996 19                                      14.361429

                      reanalysis_tdtr_k  station_avg_temp_c  \
city year weekofyear
iq   2006 7                    7.285714           28.600000
sj   1991 44                   3.042857           28.114286
     2001 12                   2.442857           26.328571
     1990 22                   3.014286           28.942857
     1996 19                   2.171429           25.442857

                      station_diur_temp_rng_c  station_max_temp_c  \
city year weekofyear
iq   2006 7                          8.900000                33.8
sj   1991 44                         7.257143                32.8
     2001 12                         7.528571                30.6
     1990 22                         9.371429                35.0
     1996 19                         6.328571                29.4

                      station_min_temp_c  station_precip_mm  total_cases
city year weekofyear
iq   2006 7                         24.2                0.0           24
sj   1991 44                        24.4                4.8          140
     2001 12                        21.7               12.7            8
     1990 22                        23.9                5.8            6
     1996 19                        21.7               10.6            6

[5 rows x 22 columns]

In [25]:
# Create working copy of the data for cleaning (df_o to remain unchanged)
df = df_o.copy()
# Data are mostly floats, with a couple ints and a couple objects
print('\n Rows and Columns:')
print(df.shape)
print('\n Data Types:')
print(df.dtypes)

 Rows and Columns:
(1456, 22)

 Data Types:
week_start_date                           object
ndvi_ne                                  float64
ndvi_nw                                  float64
ndvi_se                                  float64
ndvi_sw                                  float64
precipitation_amt_mm                     float64
reanalysis_air_temp_k                    float64
reanalysis_avg_temp_k                    float64
reanalysis_dew_point_temp_k              float64
reanalysis_max_air_temp_k                float64
reanalysis_min_air_temp_k                float64
reanalysis_precip_amt_kg_per_m2          float64
reanalysis_relative_humidity_percent     float64
reanalysis_sat_precip_amt_mm             float64
reanalysis_specific_humidity_g_per_kg    float64
reanalysis_tdtr_k                        float64
station_avg_temp_c                       float64
station_diur_temp_rng_c                  float64
station_max_temp_c                       float64
station_min_temp_c                       float64
station_precip_mm                        float64
total_cases                                int64
dtype: object

## Categorial Features

In [26]:
cat_features = df.loc[:,(df.dtypes=='object')]
cat_features.columns

Index(['week_start_date'], dtype='object')

For now we will drop week_start_date. The day of the month likely has no bearing on dengue cases, week is already represented in its own feature/column, and year should not be included in the model (though we will use the year for generation features later on).

In [27]:
df.drop('week_start_date', axis=1,inplace=True)
#df.columns

Lets look at the city attribute. (Considerating the aim is generating a model that could be applied to ***other*** regions, we should consider dropping the city attribute during training. For now week need it at least for feature generation. But I tend to think it is not appropriate to encode the city column, since in a practicaly application it should be dropped)

In [68]:
#df.index
#df.index.names
#df.index.get_level_values(0).unique()
#df.head(2)
df.loc[('sj',1990)]

C:\Users\ewell\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: PerformanceWarning: indexing past lexsort depth may impact performance.
  """

,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,reanalysis_avg_temp_k,reanalysis_dew_point_temp_k,reanalysis_max_air_temp_k,reanalysis_min_air_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
weekofyear,,,,,,,,,,,,,,,,,,,,,
18,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,297.742857,292.414286,299.8,295.9,...,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4
19,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,298.442857,293.951429,300.9,296.4,...,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5
20,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,298.878571,295.434286,300.5,297.3,...,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4
21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,299.228571,295.310000,301.4,297.0,...,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3
22,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,299.664286,295.821429,301.9,297.5,...,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6
23,NaN,0.174850,0.254314,0.181743,9.58,299.630000,299.764286,295.851429,302.4,298.1,...,79.891429,9.58,17.212857,2.100000,28.114286,6.942857,34.4,23.9,39.1,2
24,0.112900,0.092800,0.205071,0.210271,3.48,299.207143,299.221429,295.865714,301.3,297.7,...,82.000000,3.48,17.234286,2.042857,27.414286,6.771429,32.2,23.3,29.7,4
25,0.072500,0.072500,0.151471,0.133029,151.12,299.591429,299.528571,296.531429,300.6,298.4,...,83.375714,151.12,17.977143,1.571429,28.371429,7.685714,33.9,22.8,21.1,5
26,0.102450,0.146175,0.125571,0.123600,19.32,299.578571,299.557143,296.378571,302.1,297.7,...,82.768571,19.32,17.790000,1.885714,28.328571,7.385714,33.9,22.8,21.1,10
27,NaN,0.121550,0.160683,0.202567,14.41,300.154286,300.278571,296.651429,302.3,298.7,...,81.281429,14.41,18.071429,2.014286,28.328571,6.514286,33.9,24.4,1.1,6
28,0.192875,0.082350,0.191943,0.152929,22.27,299.512857,299.592857,296.041429,301.8,298.0,...,81.467143,22.27,17.418571,2.157143,27.557143,7.157143,31.7,21.7,63.7,8
29,0.291600,0.211800,0.301200,0.280667,59.17,299.667143,299.750000,296.334286,302.0,297.3,...,82.144286,59.17,17.737143,2.414286,28.128571,6.900000,32.8,23.9,12.2,2
30,0.150567,0.171700,0.226900,0.214557,16.48,299.558571,299.635714,295.960000,301.8,297.1,...,80.742857,16.48,17.341429,2.071429,28.114286,6.357143,31.7,22.8,32.6,6
31,NaN,0.247150,0.379700,0.381357,32.66,299.862857,299.950000,296.172857,303.0,298.3,...,80.584286,32.66,17.594286,2.585714,28.242857,8.085714,34.4,22.8,37.6,17
32,NaN,0.064333,0.164443,0.138857,28.80,300.391429,300.478571,296.532857,302.5,298.8,...,79.650000,28.80,17.950000,2.328571,28.200000,7.557143,33.3,23.3,11.4,23
33,NaN,0.128033,0.206957,0.168243,90.75,299.958571,299.957143,297.035714,302.6,298.5,...,84.178571,90.75,18.515714,1.857143,28.042857,6.685714,32.8,22.8,44.7,13
34,0.190233,0.168800,0.167657,0.172286,32.40,300.332857,300.414286,296.728571,302.5,298.1,...,80.947143,32.40,18.174286,2.485714,28.342857,7.014286,33.3,23.3,5.4,21
35,0.252900,0.330750,0.264171,0.284314,40.94,300.118571,300.221429,297.017143,302.2,298.7,...,83.348571,40.94,18.515714,1.900000,28.657143,6.528571,32.2,24.4,13.7,28
36,0.235400,0.200025,0.283817,0.230443,28.86,300.530000,300.635714,296.117143,303.8,298.0,...,77.172857,28.86,17.560000,3.471429,28.328571,7.614286,32.8,23.3,14.2,24
37,0.127967,0.437100,0.123400,0.148283,64.56,300.674286,300.792857,297.192857,302.9,299.0,...,81.551429,64.56,18.777143,2.900000,28.685714,8.057143,33.9,24.4,25.9,20
38,0.196350,0.182433,0.254829,0.305686,143.73,299.857143,299.900000,296.431429,301.7,298.7,...,81.637143,143.73,17.892857,1.742857,28.242857,8.114286,32.8,23.9,3.3,40
39,0.116100,0.260900,0.199443,0.244217,51.39,300.427143,300.600000,296.028571,302.4,299.1,...,77.048571,51.39,17.468571,2.257143,28.342857,7.728571,32.8,24.4,15.8,27
40,0.228550,0.189750,0.212486,0.201186,31.18,300.775714,300.850000,296.664286,303.3,299.1,...,78.520000,31.18,18.180000,2.900000,28.771429,8.028571,33.3,23.9,11.7,42
41,0.171150,0.067550,0.179467,0.157717,51.42,299.857143,299.942857,296.928571,301.8,298.1,...,84.110000,51.42,18.512857,2.571429,28.628571,7.314286,33.3,24.4,57.7,33
42,NaN,0.070200,0.181617,0.165750,143.55,299.195714,299.307143,296.544286,301.5,297.5,...,85.621429,143.55,18.115714,1.871429,27.628571,7.400000,32.8,23.3,61.8,43
43,0.146200,0.089750,0.128829,0.123929,127.03,298.902857,299.042857,296.257143,300.9,297.2,...,85.502857,127.03,17.750000,1.800000,26.771429,7.628571,32.2,21.7,91.5,37
44,0.252250,0.183433,0.318000,0.295900,101.35,299.727143,299.778571,296.534286,301.4,298.5,...,82.787143,101.35,18.034286,1.785714,27.971429,8.642857,33.3,22.8,6.3,57
45,0.152600,0.181775,0.178329,0.186629,20.46,299.972857,300.035714,296.564286,302.2,298.5,...,81.715714,20.46,18.074286,2.385714,28.471429,8.428571,33.3,23.9,6.6,71
46,0.290800,0.224600,0.180386,0.234886,20.00,300.350000,300.500000,295.687143,302.3,298.8,...,75.728571,20.00,17.085714,2.200000,27.542857,8.600000,32.8,22.2,38.9,44
47,0.272200,0.330350,0.131633,0.125383,20.04,299.511429,299.635714,295.375714,301.6,297.0,...,78.151429,20.04,16.752857,2.528571,26.800000,7.414286,31.7,22.2,9.6,56
48,0.136767,0.216525,0.176786,0.141586,33.61,298.238571,298.264286,294.811429,300.2,296.5,...,81.385714,33.61,16.208571,1.985714,26.200000,7.128571,31.1,20.6,26.7,53
49,0.109800,0.088600,0.266783,0.251700,9.96,298.542857,298.685714,294.782857,300.8,296.7,...,79.908571,9.96,16.161429,2.057143,25.985714,5.542857,29.4,22.2,69.0,52
50,0.121350,0.261660,0.191386,0.209986,0.00,298.202857,298.278571,292.004286,300.6,296.1,...,68.722857,0.00,13.615714,2.985714,24.685714,7.771429,29.4,19.4,2.8,47
51,0.293133,0.266867,0.260857,0.302729,52.45,298.297143,298.378571,294.558571,300.9,296.0,...,80.082857,52.45,15.954286,2.871429,25.714286,6.585714,30.6,21.1,19.8,26
52,0.302500,0.277233,0.171267,0.161622,0.00,298.038571,298.085714,292.105714,299.8,295.3,...,69.681429,0.00,13.682857,2.285714,25.157143,5.842857,28.9,21.1,20.9,27

ndvi_ne                                    0.032250
ndvi_nw                                    0.172967
ndvi_se                                    0.157200
ndvi_sw                                    0.170843
precipitation_amt_mm                      34.540000
reanalysis_air_temp_k                    298.781429
reanalysis_avg_temp_k                    298.878571
reanalysis_dew_point_temp_k              295.434286
reanalysis_max_air_temp_k                300.500000
reanalysis_min_air_temp_k                297.300000
reanalysis_precip_amt_kg_per_m2           26.100000
reanalysis_relative_humidity_percent      82.052857
reanalysis_sat_precip_amt_mm              34.540000
reanalysis_specific_humidity_g_per_kg     16.848571
reanalysis_tdtr_k                          2.300000
station_avg_temp_c                        26.714286
station_diur_temp_rng_c                    6.485714
station_max_temp_c                        32.200000
station_min_temp_c                        22.800000
station_precip_mm                         41.400000
total_cases                                4.000000
Name: (sj, 1990, 20), dtype: float64

Only two cities. Will do categorical encoding (though one-hot could also be used)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(["sj","iq"])
#le.classes_
df.city=le.transform(df.city)
df.head()

In [ ]:
df.dtypes

### Missing Values

In [ ]:
df.isnull().sum().sort_values(ascending=False)

In [ ]:
df[["ndvi_se","ndvi_sw","ndvi_ne","ndvi_nw"]].hist()

We could drop ndvi_ne as it is highly correlated with ndvi_nw, however currently we will try imputing with the mean of the other 3 ndvi variables. The 52 cases where ndvi_nw is missing, we will replace with the mean of ndvi_se and ndvi_sw. Where ndvi_se and ndvi_s are missing, we will impute with the mean.

In [ ]:
df.ndvi_se.fillna(df.ndvi_se.mean(),inplace=True)
df.ndvi_sw.fillna(df.ndvi_sw.mean(),inplace=True)
df.ndvi_nw.fillna((df.ndvi_sw + df.ndvi_se)/2,inplace=True)
df.ndvi_ne.fillna((df.ndvi_sw + df.ndvi_se + df.ndvi_nw)/3,inplace=True)

We will impute other rows with missing values with the mean of the respective column.

In [ ]:
df.fillna(df.mean(),inplace=True)

We will eventually going to drop year from the subesquent analysis, due to potential data leakage, but we will engineer some features using it later on.

In [ ]:
#df.drop("year", axis=1,inplace=True)
#df.columns

## Feature Analysis

So, we no longer have any categorical variable, and no missing values. No lets take a closer look at our feature.

### Target Variable - total_cases

In [ ]:
df['total_cases'].hist(bins=20)
plt.xlabel('total_cases')
plt.ylabel('count')

In [ ]:
import seaborn as sn

sn.scatterplot(x="year",y="total_cases",data=df)

## Feature Correlations

Here we define a function for displaying a correlation matrix for different features.

In [ ]:
# Let's start by looking at all features; target variable is in the last row/column
plot_corr_matrix(df=df, subset=[], details="All Features")

The bottom row and right-most column on the above correlation matrix show how each feature correlates with total cases. We observe many features that are weekly-to-moderately correlated with total_case(0.2-0.4), but none that are ***strongly*** correlated.

In [ ]:
plt.figure(figsize=(10,3.5))
#%matplotlib inline
df.corr().iloc[-1].sort_values(ascending=False).plot(kind="bar")
#plt.show()
plt.xlabel('feature')
plt.ylabel('Pearson Correaltion')
plt.title('Feature Correlation (with Target)')

**Trends (with respect to total_cases):**
* Minimum and average tempurtures are POSITIVELY correlated
* Maximum tempurtures and tempurture rangers are NEGATIVELY correlated

In [ ]:
exclude_labels=['year']

In [ ]:
df.columns

In [ ]:
df=move_target_to_end(df,'total_cases')

In [ ]:
high_corr_feat = select_top_features(df,n_features=10)
print(high_corr_feat)

In [ ]:
# Check the correlation matrices for the ndvi features, before and after imputation
plot_corr_matrix(df=df_o, subset=['ndvi_ne','ndvi_nw','ndvi_se','ndvi_se'], details="original") 
plot_corr_matrix(df=df, subset=['ndvi_ne','ndvi_nw','ndvi_se','ndvi_se'], details="imputed")

No lets look how the data are distributed.

In [ ]:
_=pd.plotting.scatter_matrix(df[high_corr_feat], figsize=(15,15))

### Measurement Disparity Before/After year 2000

Look at the year row, it looks like something strang is happening reguarding data before and after ~2000 for several of the attributes: **reanalysis_min_air_temp_k, reanalysis_tdtr_k, station_diur_temp_rng_c, and reanalysis_max_air_temp_k***. For all of these feature, values are much more dispersed PRIOR to 2000. Let's take for example: reanalysis_min_air_temp_k.

In [ ]:
sn.scatterplot(df["year"],df["reanalysis_min_air_temp_k"])

It is unlikely that after 2000, minumum air temps dropped that dramatically and consistently. And it's the same for most other realated variable.

In [ ]:
import math
df2=df.copy()
df2['log_total_cases']=np.log(df2['total_cases']+.001)
df2.sample(10)

In [ ]:
fig,ax = plt.subplots(4,2, figsize=(7,7))
#sca=axes[0,0]
plt.subplots_adjust(wspace=.4)
sn.scatterplot(x="year",y="reanalysis_min_air_temp_k",data=df2, ax=ax[0,0],hue="log_total_cases",legend=False)
sn.scatterplot(x="year",y="reanalysis_max_air_temp_k",data=df2, ax=ax[0,1],hue="log_total_cases",legend=False)
sn.scatterplot(x="year",y="station_min_temp_c",data=df2, ax=ax[1,0],hue="log_total_cases",legend=False)
sn.scatterplot(x="year",y="station_max_temp_c",data=df2, ax=ax[1,1],hue="log_total_cases",legend=False)
sn.scatterplot(x="year",y="reanalysis_tdtr_k",data=df2, ax=ax[2,0],hue="log_total_cases",legend=False)
sn.scatterplot(x="year",y="station_diur_temp_rng_c",data=df2, ax=ax[2,1],hue="log_total_cases",legend=False)
sn.scatterplot(x="year",y="station_avg_temp_c",data=df2, ax=ax[3,0],hue="log_total_cases",legend=False)
sn.scatterplot(x="year",y="reanalysis_avg_temp_k",data=df2, ax=ax[3,1],hue="log_total_cases",legend=False)

Across the board, temperture ranges were smaller before 2000. But the effect is less noticible in the "station" measurents. ~10-deg range disparity for "realanalysi"; only ~5-deg disparity for station. 

This stongly indicates some sort of measurement bias/error (perhaps new equipement was established in 200). This needs to be accounted for with some sort o correction. 

A simply approach would be an indicator variable for before/after 2000. See this below in Feature Engineering section.

### Exploring time series

Here I'll explore the features that vary by week. That's all the weather related features ("station " and "reanalysis "), which are weekly measurements of things like rain, max temp, min temp, daily temp range, dew point, etc. 

Since Dengue is a mosquito born virus, it's important to keep in mind the life cycle of a mosiquito. Say, it takes about two weeks from egg laying until mosquitos can fly (1.5 weeks is about the minimum, but could be up to month or longer). Clearly, the weather patterns of two weeks ago, if they influence egg laying, would have an inpact on current denque infections. A longer than two week lag if you factor in gestational duration in an infected human prior to being simptomatic. (The incubation period ranges 3-17 days from, with 4-7 being most common)

This well be explored further in the Feature Engineering section.

In [ ]:
df.columns

In [ ]:
def plot_v_week(df, att, Year):
    xx = df.weekofyear.loc[df.year==Year]
    yy = df[att].loc[df.year==Year]
    sn.lineplot(xx,yy)

In [ ]:
att = 'total_cases'
Year = df.year.min()
plot_v_week(df, att, Year)

In [29]:
att = 'reanalysis_min_air_temp_k'
Year = df.year.min()
plot_v_week(df, att, Year)

AttributeError: 'DataFrame' object has no attribute 'year'

In [ ]:
att = 'station_min_temp_c'
Year = df.year.min()
plot_v_week(df, att, Year)

In [ ]:
att = 'station_precip_mm'
Year = df.year.min()
plot_v_week(df, att, Year)



## Prepare the Data 

### Split into x and y

In [ ]:
def split_xy(df,drop_atts):
    X = df.copy()
    X.drop(drop_atts, axis=1, inplace=True)
    Y = df.total_cases
    return X,Y

In [ ]:
x,y = split_xy(df,drop_atts =["total_cases","year"])
x.columns

In [ ]:
#numberical featuers (all feature should now be numerical)
#num_features = x.loc[:,(df.dtypes=='int64')|(df.dtypes=='float64')|(df.dtypes=='int32')]
#num_features.columns
#num_features.dtypes

In [ ]:
df.columns

## Baseline Negitive Bionomial Model

Now that we've done some basic data exploration and cleaning, let's do a preliminarly linear regression before any feature engineering. This will serve as starting point. We will just take numerical features--we will explore categorical encoding a bit later on. 

First let's funcationalize our linear regression model.

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

In [ ]:
# Baseline Linear regression, no bell/whistles, to get a starting point
# all numerical features
lin_reg(x,y)

In [ ]:
# Baseline scores for decision tree
dtree_reg(x,y)

In [ ]:
# Baseline scores for decision tree
randfor_reg(x,y)

In [ ]:
high_corr_feat = select_top_features(df,n_features=6)
print(high_corr_feat)

In [ ]:
high_corr_feat

In [ ]:
# Baseline Linear regression, but with a subset of features
lin_reg(x,y,features=high_corr_feat)

Selecting the 10 best features greatly benefits the linear regression model, but has a negative impact on the tree methods, as shown in the outputs of the next two cells.

In [ ]:
# Baseline scores for decision tree
dtree_reg(x,y,features=high_corr_feat)

In [ ]:
# Baseline scores for decision tree
randfor_reg(x,y,features=high_corr_feat)

So, we're clearly starting from a place of poor prediction. Plenty of room for improvement!

The plan going forward is to:
* Perform categorical encoding for our categorical feature
* Engineer some features
* Explore some other regression models and choose 2-3 to fine-tune
* Optimize our chosen models using regularization and gridsearc

## Feature Engineering

### Prior Time-point Features

In [ ]:
def att_prev_week(df, att, new_label,num_weeks=1):
    
    """For a given attribute (att) and number of weeks earlier we wish to look at (num_weeks)
    this function returns (for every row) the value of att, number_weeks prior. A new column 
    with the appened label is returned"""
    t = []
    for i in range(len(df)):    
        prev_val = []
        #row = df.iloc[i]
        Year = df.year.iloc[i]
        City = df.city.iloc[i]
        Week = df.weekofyear.iloc[i]
        #print(Year,City,Week)

        if Week<=(1+(num_weeks-1)):
            prev_val = df[att].loc[(df.city==City)&(df.year==Year)&(df.weekofyear==Week-num_weeks)]
        # This else only catches week = 1 if year is not 1990. now previous week in that case
        elif (Week>(1+(num_weeks-1)))&(Year!=df.year.min):
            prev_val = df[att].loc[(df.city==City)&(df.year==Year-1)&(df.weekofyear==(52-(num_weeks-1)))]
        else:
            #
            prev_val = df[att].loc[(df.city==City)&(df.year==Year)&(df.weekofyear)]

        #print(prev_val.values)
        if len(prev_val)==0:
            prev_val = df[att].loc[(df.city==City)&(df.year==Year)&(df.weekofyear)]
        t.append(prev_val.values[0])
    df[new_label] = t
    print(new_label)
    return t

['prev2_week_re_max_temp',
 'city',
 're_max_over_min',
 'reanalysis_tdtr_k',
 'prev_week_re_max_temp',
 'reanalysis_max_air_temp_k',
 'station_diur_temp_rng_c',
 'reanalysis_min_air_temp_k',
 'prev2_week_re_min_temp',
 'station_max_over_min']

In [ ]:
select_top_features(df,n_features=10)

In [ ]:
df.columns

In [ ]:
atts=['precipitation_amt_mm', 'reanalysis_air_temp_k',
       'reanalysis_avg_temp_k', 'reanalysis_dew_point_temp_k',
       'reanalysis_max_air_temp_k', 'reanalysis_min_air_temp_k',
       'reanalysis_precip_amt_kg_per_m2',
       'reanalysis_relative_humidity_percent', 'reanalysis_sat_precip_amt_mm',
       'reanalysis_specific_humidity_g_per_kg', 'reanalysis_tdtr_k',
       'station_avg_temp_c', 'station_diur_temp_rng_c', 'station_max_temp_c',
       'station_min_temp_c', 'station_precip_mm']
weeks = [1,2,3,4]

In [ ]:
def generate_prior_features(atts,weeks):
    for att in atts:
        for week in weeks:
            new_att = att+'_prev'+str(week)
            print(new_att)
            _=att_prev_week(df, att,new_att,num_weeks=week)
        
generate_prior_features(atts,weeks)

In [ ]:
df=move_target_to_end(df,'total_cases')

In [ ]:
df.columns

In [ ]:
# Display a smaller feature space of the new features

prior_feats = df.columns[26:]
#len(prior_feats)
fold = 4
R = max(weeks)*4
s1=(fold-1)*R+1
s2=fold*R+1
prior_feats1 = list(prior_feats[s1:s2])
#print(prior_feats1)
prior_feats1.append('total_cases')

plot_corr_matrix(df=df, subset=prior_feats1, details="Prior Timepoint Features")

In [ ]:
plt.figure(figsize=(10,3.5))
#%matplotlib inline
df[prior_feats].corr().iloc[-1].sort_values(ascending=False).plot(kind="bar")
#plt.show()
#plt.xlabel('feature')
plt.ylabel('Pearson Correaltion')
plt.title('Feature Correlation (with Target)--Prior time-point feature')

In [ ]:
select_top_features(df,n_features=10)

As metioned earlier, there is somesort of discrepancy between temperture reading before/after the year 2000. So for know we'll create and indicator for that. However, ultimately we should implement a correction, because this feature will not be appropriate for new instances (meaning those that occur in the future--by definition after the year 2000).

In [ ]:
def before_2000(year):
    if year < 2000:
        return 0
    else:
        return 1
    
df['before_2000'] = df['year'].apply(before_2000)

In [ ]:
df.columns

In [ ]:
sn.scatterplot(x='weekofyear',y='total_cases',data=df)

In [ ]:
def week_season(weekofyear):
    if (weekofyear<=22)&(weekofyear>=10):
        return 0
    elif (weekofyear<10):        
        return 1
    else:
        return 2
    
df['week_season'] = df['weekofyear'].apply(week_season)

In [ ]:
df['re_max_over_min'] = df.reanalysis_max_air_temp_k/df.reanalysis_min_air_temp_k

In [ ]:
df['station_max_over_min'] = df.station_max_temp_c/df.station_min_temp_c

In [ ]:
df.columns

In [ ]:
x,y = split_xy(df,drop_atts =["total_cases","year"])
#x.columns

In [ ]:
lin_reg(x,y,features=select_top_features(df,n_features=20))

In [ ]:
randfor_reg(x,y,features = select_top_features(df,n_features=11))

In [ ]:
from sklearn.preprocessing import PowerTransformer

def lin_reg_pow(x,y, features=[],do_scale=True, show_cm=False,normTF=True):
    """ Linear Regressio with Power Tranformer"""    
    if len(features)>0:
        #print(len(features)>0)
        x=x[features]
    
    x_train, x_val, y_train, y_val = train_test_split(x,y,test_size=0.2,random_state=3)
    
    model = LinearRegression()
    if do_scale:
        regressor = Pipeline(steps = [('scaler',PowerTransformer()),('model',model)])
    else:
        regressor = Pipeline(steps = [('model',model)])
        
    regressor.fit(x_train,y_train)
    y_predict = regressor.predict(x_val)
    
    scores = cross_val_score(regressor, x, y, cv=5, scoring='neg_mean_squared_error')
    print("RMSE: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
    
    # Display some random validation vs predicted y pairs
    rand_samp = list(np.random.choice(range(len(y_val)),10,replace=False))
    y_top = np.array(y_val.iloc[rand_samp])
    # Rounding the predicted values for display purposes
    yp_top = np.array(y_predict[rand_samp]).round()
    
    Y = np.array([y_top,yp_top]).T
    print(Y)

In [ ]:
lin_reg_pow(x,y,features = select_top_features(df,n_features=26))

One feature to engineer is an obvious one: number of case for the same city in the previous year. While we are at it, we could do it for a range of previous years. Lets limit it at 3.  The year range for this data is 1990-2010. So if we want to do a feature for each of the 3 previous year, problems arrise for 1990, 1991,and 1992. 1991 and 92 both have data avaible for **one** year previous, but 92 does not have data for **three** years previous, and and 91 does not for **two or three** years prior. So those years will have to be dealt with differently.

In [ ]:
df.shape

In [ ]:
#df.sample(5)
#df.set_index(['city','year','weekofyear'],inplace=True)
#df.reset_index(inplace=True)
df.sample(5)

In [ ]:
#years = (list(range(1993,2011)))
#df_sub=df.loc[(df.year<=2010)&(df.year>=1993)]
#print(years)
#df_sub=df.loc[df.year.isin(years)]
#df_sub.tail()

In [ ]:
#for i in range(len(df_sub)):
#    case_one_prior= df.loc[(df.city == df_sub.iloc[i].city)&(df.weekofyear == df_sub.iloc[i].weekofyear)&
#                           (df.year == (df_sub.iloc[i].year-1))].total_cases

In [ ]:
#(df.city == df_sub.iloc[i].city)&(df.weekofyear == df_sub.iloc[i].weekofyear)&(df.year == (df_sub.iloc[i].year-1))

### PCA Feature Reduction

In [ ]:
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV

x_train, x_val, y_train, y_val = train_test_split(x,y,test_size=0.2,random_state=3)

pca = PCA()
lin_reg = LinearRegression()
pipe = Pipeline(steps=[('pca', pca), ('lin_reg',lin_reg)])

param_grid = {
    'pca__n_components': [5, 20, 30, 40],
}
search = GridSearchCV(pipe, param_grid, iid=False, cv=5,scoring = 'neg_mean_squared_error')
search.fit(x_train, y_train)

In [ ]:
pca = PCA(n_components=5)
lin_reg = LinearRegression()
pipe = Pipeline(steps=[('scaler',StandardScaler()),('pca', pca), ('lin_reg',lin_reg)])

pipe.fit(x_train, y_train)
y_predict = pipe.predict(x_val)

scores = cross_val_score(pipe, x, y, cv=5, scoring='neg_mean_squared_error')
print("RMSE: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

# Display some random validation vs predicted y pairs
rand_samp = list(np.random.choice(range(len(y_val)),10,replace=False))
y_top = np.array(y_val.iloc[rand_samp])
# Rounding the predicted values for display purposes
yp_top = np.array(y_predict[rand_samp]).round()

Y = np.array([y_top,yp_top]).T
print(Y)

In [ ]:
pcapt = PCA().fit(x)
plt.plot(np.cumsum(pcapt.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance');

In [ ]:
scores = cross_val_score(search, x, y, cv=5, scoring='neg_mean_squared_error')
print("RMSE: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [ ]:
#print_gridsearch_results(search,x_val,y_val)

## Model Selection

We will contiue to explore the linear regression model (lasso/ridge/elasticnet regularization explored later), but well will also investicate SVMs, Naive Bayes, Decision Trees. Ensemble methods will be exlored later on.

In [ ]:
import xgboost as xgb
param_dist = {'objective':'count:poisson', 'n_estimators':17}

clf = xgb.XGBModel(**param_dist)

clf.fit(X_train, y_train,
        eval_set=[(x_train, y_train), (x_val, y_val)],
        eval_metric='rmse',
        verbose=True)

evals_result = clf.evals_result()